

package com.tebi.ktn.testing.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.tebi.ktn.testing.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/src/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class JvmBoxTestGenerated extends AbstractJvmBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/src/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("Mixed.kt")
  public void testMixed() {
    runTest("compiler-plugin/src/testData/box/Mixed.kt");
  }

  @Test
  @TestMetadata("QualifiedName.kt")
  public void testQualifiedName() {
    runTest("compiler-plugin/src/testData/box/QualifiedName.kt");
  }

  @Test
  @TestMetadata("SimpleName.kt")
  public void testSimpleName() {
    runTest("compiler-plugin/src/testData/box/SimpleName.kt");
  }
}
